### ISSUE TITLE
Incorrect "Command from Ground:" status

### ISSUE THREAD

**Issue by DickvanNoort** [TLeconte/vdlm2dec#11]
The "Command from Ground: 3C4AAB to 214AB7 " suggest that 3C4AAB is a ground station, which is not the case.
A compare with the dumpvdl2 log shows that the aircraft reports an "on the ground" status.

vdlm2dec message:
[#5 (F:136.975 P:-5.1) 25/01/2018 12:01:10.361 --------------------------------
Command from Ground: 3C4AAB to 214AB7 
Frame-I: Ns:0 Nr:0
ACARS
Aircraft reg: D-ABUK Flight id: DE2062
Mode: 2 Msg. label: Q0
Block id: 5 Ack: !
Msg. no: S24A
Message :

Same message but now from dumpvdl2:
[2018-01-25 12:01:10 GMT] [136.975] [-45.6/-52.3 dBFS] [6.7 dB]
3C4AAB (Aircraft, On ground) -> 214AB7 (Ground station): Command
AVLC type: I sseq: 0 rseq: 0 poll: 0
ACARS:
Reg: .D-ABUK Flight: DE2062
Mode: 2 Label: Q0 Blk id: 5 Ack: ! Msg no.: S24A
Message:

**Comment by TLeconte** [comment]
fixed
