### ISSUE TITLE
Acars Messages

### ISSUE THREAD

**Issue by acarslogger** [TLeconte/vdlm2dec#13]
Using vdlm2dec, I'm receiving acars messages similar to ...
```
[#5 (F:136.975 P:-5.2) 01/02/2018 06:35:57.089 --------------------------------
Command from Aircraft:4B17E5 (airborne) to GroundD:10902A 
Frame-I: Ns:5 Nr:4
ACARS
Aircraft reg: HB-JBH Flight id: LX0450
Mode: 2 Msg. label: H1
Block id: 7 Ack: !
Msg. no: 701A
Message :
#T7B- R001
ACARS Header
 HB-JBH,5318410-02,649537,200637,01631,LSZH,EGLC,06:13:14,2018:02:01,00000000
000010,152000
    0.76 (06:21:35)
0.000,0.000,0.000,0.000,03b15,03aa5,00001,0.312,0.000,21.984,22.727,00001

Block End
```
and ...

```
[#5 (F:136.975 P:-5.2) 01/02/2018 06:36:14.522 --------------------------------
Command from Aircraft:4B17E5 (airborne) to GroundD:10902A 
Frame-I: Ns:1 Nr:0
ACARS
Aircraft reg: HB-JBH Flight id: LX0450
Mode: 2 Msg. label: H1
Block id: 1 Ack: !
Msg. no: 701E
Message :
#T7B99.625,98.578,159.688,70.375,2.844,2.250,535.562,530.812,124.953,130.031
101.781,97.516,99.750,102.250,-113.000,-54.000,88.250,88.250,1800.000,1869.500
397.500,386.500,1674.000
ACARS Footer:  
```
I assume that the text 'ACARS' defines the start of an acars message, but what are '**ACARS Header**' and '**ACARS Footer**'? Are they part of the actual aircraft acars message or debug information? Can they be removed?

Likewise there are number of messages that end with a '**Block End**' text. Is this part of the acars message or debug info?

Stuart

**Comment by TLeconte** [comment]
Yes ACARS defines the start of an ACARS message
Block End is part of acars message ( special character 0x17).
Don't known about ACARS Header/Footer , there is not such things in my sources  ???
Perhaps there are just part of your received message ...

**Comment by acarslogger** [comment]
Apologies. I hadn't noticed the Acars Header/Footer before. It appears in the last couple of weeks that Swiss have implement new acars software which now includes this text.
