### ISSUE TITLE
Add "By default use maximum gain" to description  -g attribute 

### ISSUE THREAD

**Issue by DickvanNoort** [TLeconte/vdlm2dec#16]
The readme and help state: 
-g gain :  set rtl preamp gain in tenth of db (ie -g 90 for +9db).

In acarsdec this attribute mentions:
-g gain :  set rtl preamp gain in tenth of db (ie -g 90 for +9db). By default use maximum gain
Based on the messages vdlm2dec displays at startup 
"Tuner gain : 49.600000"
I assume the "By default use maximum gain" is also true for vdlm2dec.

**Comment by TLeconte** [comment]
fixed
