### ISSUE TITLE
Were should I put the -g attribute in the command string?

### ISSUE THREAD

**Issue by DickvanNoort** [TLeconte/vdlm2dec#17]
Trying to use the -g attribute but so far failed.
Tried different places in the string like:
/home/pi/vdlm2dec/vdlm2dec -g 280 -r 00000011  136.725 136.775 136.875 136.975
/home/pi/vdlm2dec/vdlm2dec -r 00000011 -g 280 -p -1 136.725 136.775 136.875 136.975
etc.

I always get warnings and/or only the "usage" display.

**Comment by TLeconte** [comment]
Now that I have  fixed gain setting for rtlsdr , the good syntax is the former . 
-r must always be the last option before frequencies.
