### ISSUE TITLE
JSON Output - Aircraft ICAO Code

### ISSUE THREAD

**Issue by acarslogger** [TLeconte/vdlm2dec#19]
The JSON outputs (-j and -J) have the aircraft ICAO code included as a decimal value. It would be clearer to include the icao code as it's normally displayed as a Hex character string e.g. 400DAD ?

Stuart

**Comment by TLeconte** [comment]
Yes , I hesitated on this one.
It's sure , it's better to have the hex value for human reading, but json is more for  information exchange between computers.
icao addresses are 24bits values, so using an integer seemsmore logical than using a string encoding a hex value ...

**Comment by acarslogger** [comment]
I understand that reasoning. Keep as integer.
Stuart
