### ISSUE TITLE
Channel Number output - base 0 or 1

### ISSUE THREAD

**Issue by acarslogger** [TLeconte/vdlm2dec#21]
Hi Thierry,

My vdlm2dec command line has the first frequency defined as 136.725.
The default log file output shows this as 
> [#1 (F:136.725 P:-1.5) 10/02/2018 ..... i.e <channel 1>

The equivalent JSON output shows as "
> channel":0,"freq":136.725, ..... i.e. <channel 0>

The default log file appears to show the channel number as base 1. The JSON output appears to be base 0.
Both outputs are independant so it doesn't really make any significant difference, but would it be better for consistency if they were both base 0 or 1?

I haven't checked yet if this also applies to acarsdec.
***edit -- same applies to acarsdec***
Regards
Stuart

**Comment by TLeconte** [comment]
Yes your right, it will be better for consistency, but worse for compatibility.
The log output format dated from acarsdec (a long time ago), and the json code was contributed (ie not written by me). 
I fear i will let thins like that. I don't want to break things
