### ISSUE TITLE
A new logfile is created at midnight of the timezone.  Better to do it at midnight UTC

### ISSUE THREAD

**Issue by DickvanNoort** [TLeconte/vdlm2dec#25]
My RPi uses timezone Amsterdam which is CEST.
The current version of vdlm2dec logs the messages in UTC but creates a new logfile at midnight CEST.
Please create a new logfile at midnight UTC.

Thanks,
Dick

**Comment by TLeconte** [comment]
?????
vdlm2dec don't  create new logs. Just append to the given file name.
It must be something else that restart vdlm2dec and create new log.
