### ISSUE TITLE
Various Decoding Issues

### ISSUE THREAD

**Issue by acarslogger** [TLeconte/vdlm2dec#3]
I'm an aviation enthusiast, not a C developer.

Issue 1
No mention of the -v options in the README although they appear in usage()
The -v output options shows 3 values 0, 1 & 2. Source code allows for an additional 4th option "-v 3". What is this?

Issue 2
Need to add a date and time stamp (in UTC) to every message for all output formats.

Issue 3
I'd prefer the frequency in place of the channel number. See issue on the 'acarsdec' Github.

Issue 4
The aircraft 6 character identifier (ModeS/ICAO24) appear to be incorrect. Example ...

**#1 Command from Aircraft: 50a130 to: 08100a 
Frame-I: -/- Ns:4 Nr:6
ACARS
Aircraft reg: G-EZFN Flight id: U229PF
Mode: 2** ......

The message above shows the aircraft registration as G-EZFN. According to look-up sites the Identifier/ModeS/ICAO24 for G-EZFN should be 406130. You have 50a130.

Issue 5
A VDL2 broadcast message from a ground station e.g.

**#5 Command from Ground: 278f37 to: ffffff 
Frame-U: -/- XID
Parameter set ID
Procedure classes
HDLC options**
.....

shows the ground station id as 278f37. This is my local EGLC ground station which should have an id of 260F37

Issue 6
For broadcast messages, other VDL2 decoding software decode the the data in the broadcast message e.g.
Name: EGLC
Location: 51.5N 0.0E

Issue 7
Add a UDP output. There have been various discussions regards UDP output for 'acarsdec' on Github. Maybe similar for this application.

Stuart

**Comment by TLeconte** [comment]
Hi
Thanks for your interest in vdlm2dec
Please, when you  have more than one issue, create  a  github issue for each one. It's easier to manage.

#1 Yes -v option is not really clean . It's why I don't document it in README . forget that it's in usage ..
#2  ok but perhaps not for all format
#3 the plan is to have the same json output for acarsdec and vdlm2dec, with frequencies
#4 That's  a real big bug. I will check it today.

Edit : #4 : seems that the 3 top half octet are  wrong  :-(

**Comment by TLeconte** [comment]
#4 fixed
 brown paper bag bug (see the diff :-) )

Thanks a lot for the report

Note : #5 is same as #4

**Comment by TLeconte** [comment]
Fixed #2

**Comment by TLeconte** [comment]
Could you give an example of #6 output with -v3

**Comment by acarslogger** [comment]
Apologies for not knowing the github conventions and combining different issues into one. If you close this issue, I'll create new issues for the data within a Broadcast Message and another to keep track of the proposed JSON UDP feed.
In future I'll raise separate issues. As I'm not a c developer and can't generate Pull Requests, so is it OK for me to add requests/suggestions as an Github issue?

**Comment by TLeconte** [comment]
Yes no problem , you could flag issues as bug or enhancement request

Most of your issues are now fixed in particular the infamous #4/#5
For the json  UDP feed, it's in the plan so just give me some time. A new issue is not really necessary. It will be done.

I let this issue open for #6 that I don't really understand.
Could you give me an example with -v 3 of such a broadcast message which is not decoded.
I  don't live near a ground station so I receive very few  ground messages...

**Comment by TLeconte** [comment]
As you opened new dedicated issues (as asked); I close this more general one
