### ISSUE TITLE
High CPU Use

### ISSUE THREAD

**Issue by acarslogger** [TLeconte/vdlm2dec#36]
Hi Thierry,

I'm running the latest commit cf6d0724571dad9b505832903983b78c1d9e009c with the new -b and libacars.
Previous versions have used about 45% of cpu on my Raspberry Pi v3.
When using 'top', this latest version appears to be running at 195% cpu; although I assume it is spread across all cpu's.
Why is the CPU use so high?
Regards
Stuart

**Comment by TLeconte** [comment]
Strange. I did not change the signal processing code which is the part that consume CPU.
I think it's more a Makefile vs CMake  problem.
I naively hoped that CMake will use the good compile options depending of target.

Could you try to add to CMakeLists.txt the line :
add_compile_options(-O3 -mcpu=cortex-a53  -mfpu=neon-fp-armv8)
just  BEFORE add_executable.

Then 
rm -rf build
and then redo all the compile procedure (make build  etc ...)

I do that blindly as I don't have a RP3

**Comment by TLeconte** [comment]
Sorry
The line add_compile_options must  be BEFORE add_executable

**Comment by acarslogger** [comment]
Hi Thierry,

Changed the CMakeLists.txt file. It's now reduced the cpu from 195% down to about 65%. Thanks.
As a matter of interest I've tried running both the old version (with the old Makefile) and new version (with CMake) on the Raspberry Pi at the same time. Both using similar RTL-SDR v3. The original version runs at about 50 to 55% cpu, the latest version runs at 65 to 70%.
Regards
Stuart

**Comment by TLeconte** [comment]
Not normal; 
What compile options did you use in the Makefile for the RP3 ?

**Comment by TLeconte** [comment]
I added a generic  add_compile_options to CMakeLists.txt and add a comment in README for ARM boards.
