### ISSUE TITLE
More support for Airspy?

### ISSUE THREAD

**Issue by jmhayes-table** [TLeconte/vdlm2dec#38]
My airspy only supports 10 and 2.5MSPS, but in vdl2.h I see:

`#define` SDRINRATE 5000000
#define SDRCLK  `1250`

So when I build for airspy and run, it says it can't find the requested scan rate.  Using what you did for the Mini, I tried 2500000/625 and commented out the two calls to `airspy_r820t_write()` and now it opens the device, but doesn't seem to decode any data?

`$ airspy_info
airspy_lib_version: 1.0.7

Found AirSpy board 1
Board ID Number: 0 (AIRSPY)
Firmware Version: AirSpy NOS v1.0.0-rc1-2-g64b62c3 64b62c3-dirty 2014-11-24
Part ID Number: 0x6906002B 0x00000030
Serial Number: 0x440464C83868664F
Supported sample rates:
        10.000000 MSPS
        2.500000 MSPS
Close board 1`

**Comment by TLeconte** [comment]
10 and 2.5 MSPS are for IQ format
vdlm2dev use raw format.
Are you sure that your lib and firmware are up to date ?
I have seems problems in the past with old versions.
