### ISSUE TITLE
Tag Versions?

### ISSUE THREAD

**Issue by kevinelliott** [TLeconte/vdlm2dec#51]
Hey @TLeconte,

I'm building some packages for `vdlm2dec` and `acarsdec` for inclusion on ReceiverOS (previously AROS, a project from https://github.com/airframesio). Do you think we can start adding version tags on the repository again? I'd like to be able to properly version the packages against known releases.

Thanks!

**Comment by kevinelliott** [comment]
Preferably with semver (`v3.7.0`).

**Comment by TLeconte** [comment]
Everything happends one day : v2.2 is out and tagged
