### ISSUE TITLE
Typo in outacars.c when setting fl->oooi.lon

### ISSUE THREAD

**Issue by x31415926** [TLeconte/vdlm2dec#57]
The code in [outacars.c](https://github.com/TLeconte/vdlm2dec/blob/master/outacars.c#L316) for `int outacars(flight_t *fl,unsigned char *txt, int len)` looks like this:
```
if(oooi.epu) {
    fl->oooi.epu=oooi.epu;
    fl->oooi.lat=oooi.lat;
    fl->oooi.lat=oooi.lon;
}
```

Should set `oooi.lon`, not `oooi.lat`, on the last line.

**Comment by TLeconte** [comment]
Thanks.
I commited the fix
