### ISSUE TITLE
Feature: Use RTL serialnumber to select the dongle

### ISSUE THREAD

**Issue by DickvanNoort** [TLeconte/vdlm2dec#7]
When one has multiple dongles connected using the device ID can be confusing.
Please implement the use of serialnumber.
There are several examples on github that have this feature (like dumpvdl2).. 

Cheers,
Dick

**Comment by DickvanNoort** [comment]
Appologies, I was interpreting the error messages wrongly.
The program already support using the SN of the dongle.

Cheers,
Dick

**Comment by TLeconte** [comment]
yes but it's nor really clear in the doc.
I have to do something about it.

**Comment by DickvanNoort** [comment]
Hi Thierry,

As long as the program is not stable and only a few testers are suing it the documenting the features and arguments could be a low priority.

The current version which I downloaded and compiled this morning does not decode at all..
But I suppose you already know that.

Cheers,
Dick
