### ISSUE TITLE
Logfile Creation (Request)

### ISSUE THREAD

**Issue by acarslogger** [TLeconte/vdlm2dec#8]
The current logging mechanism creates a log file when vdlm2dec starts, and continues to append to it until the application is stopped.
Would it be possible to enhance the logging option so that a new file is created at midnight UTC so that we get daily log files. (also applies to acarsdec) e.g. 20180120.txt, 20180121.txt etc.

**Comment by TLeconte** [comment]
You could easily script that and put it in the  crontab
